name: Keep Supabase Alive

on:
  schedule:
    - cron: '* */1 * * *'  # Executar a cada 1 minuto

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Keep Supabase Alive
      run: |
        # Substitua as variáveis abaixo pelas suas credenciais e informações do projeto Supabase
        export SUPABASE_URL=https://kbepchfnyekginxgukoi.supabase.co
        export SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiZXBjaGZueWVrZ2lueGd1a29pIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjgyNjQ1NjYsImV4cCI6MTk4Mzg0MDU2Nn0.ZzyQcGG0HS5MO3_oO8r1PCe10cWFsd9dW8yn4-nXYDA

        # Fazer chamada à API do Supabase para manter o projeto ativo
        curl -X POST "${SUPABASE_URL}/rest/v1/request" -H "apikey: ${SUPABASE_KEY}"
